<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\bin.png" />
    <None Remove="Icons\download.png" />
    <None Remove="Icons\file_image.png" />
    <None Remove="Icons\paper_clip.png" />
    <None Remove="Icons\power.png" />
    <None Remove="Icons\power_off.png" />
    <None Remove="Icons\power_on.png" />
    <None Remove="Icons\send_fill.png" />
    <None Remove="Icons\send_fill_active.png" />
    <None Remove="Icons\smiley.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\bin.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\download.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\file_generic.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\file_image.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\paper_clip.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\power.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\power_off.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\power_on.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\send_fill.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\send_fill_active.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\smiley.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
    <PackageReference Include="iNKORE.UI.WPF.Emojis" Version="0.3.6.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetProtocol\NetProtocol.csproj" />
    <ProjectReference Include="..\Utils\Utils.csproj" />
  </ItemGroup>

</Project>
